# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the develop branch
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ windows-2019, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15 ]
                bazel: [ 3.7.1, 3.7.0, 4.0.0 ]

        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}

        # Set job name
        name: OS ${{ matrix.os }} bazel ${{ matrix.bazel }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - uses: seanmiddleditch/gha-setup-ninja@master

            - name: Setup Bazelisk
              uses: bazelbuild/setup-bazelisk@v1.0.1

            - name: Install Ubuntu Dependencies
              if: ${{ matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04' }}
              run: sudo apt-get install -y libgl-dev libgl1-mesa-dev libx11-dev mesa-common-dev libglu1-mesa-dev libxxf86vm-dev libxcursor-dev libpango1.0-dev libpangocairo-1.0-0 libcairo2-dev

            - name: Install MacOS Dependencies
              if: ${{ matrix.os == 'macos-11.0' || matrix.os == 'macos-10.15' }}
              run: |
                brew install openssl
                ln -s /usr/local/opt/openssl/include/openssl /usr/local/include
                ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/

            - name: Build & Test All
              run: |
                bazel test //tests:test_all
              env:
                USE_BAZEL_VERSION: ${{ matrix.bazel }}
